name: build and run
on:
  - push
permissions:
  contents: read
  pages: write
  id-token: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'oracle'
    - name: Run tests
      run: mvn test
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'oracle'
    - name: set version
      run: mvn versions:set -DnewVersion=${{ github.sha }}
    - name: generate Javadocs
      run: mvn javadoc:javadoc
    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'target/site/apidocs'
    - name: push Javadocs to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1